//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Segmentation.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Segmentation.Configuration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;AnatomicCodes xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;AnatomicRegionAndModifier.xsd&quot;&gt;
        ///  &lt;AnatomicRegion SNOMEDCTConceptID=&quot;91750005&quot; UMLSConceptUID=&quot;C0524430&quot; cid=&quot;3014&quot; codeMeaning=&quot;1st Diagonal Coronary Artery&quot; codeValue=&quot;T-43117&quot; codingScheme=&quot;SRT&quot; contextGroupName=&quot;Coronary Artery Segments&quot; /&gt;
        ///  &lt;AnatomicRegion SNOMEDCTConceptID=&quot;&quot; UMLSConceptUID=&quot;&quot; cid=&quot;3014&quot; codeMeaning=&quot;1st Diagonal Coronary Artery La [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnatomicRegionAndModifierXml {
            get {
                return ResourceManager.GetString("AnatomicRegionAndModifierXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:element name=&quot;AnatomicCodes&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///				&lt;xs:element name=&quot;AnatomicRegion&quot;&gt;
        ///					&lt;xs:complexType&gt;
        ///						&lt;xs:sequence minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///							&lt;xs:element name=&quot;Modifier&quot;&gt;
        ///								&lt;xs:complexType&gt;
        ///									&lt;xs:attribute name=&quot;codeValue&quot; type=&quot;xs:string&quot; use=&quot;requ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnatomicRegionAndModifierXsd {
            get {
                return ResourceManager.GetString("AnatomicRegionAndModifierXsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SegmentationCodes xsi:noNamespaceSchemaLocation=&quot;SegmentationCategoryTypeModifier.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Category codingScheme=&quot;SRT&quot; codeValue=&quot;T-D0050&quot; codeMeaning=&quot;Tissue&quot; cid=&quot;7051&quot; contextGroupName=&quot;Segmentation Property Categories&quot; SNOMEDCTConceptID=&quot;85756007&quot; UMLSConceptUID=&quot;C0040300&quot; showAnatomy=&quot;true&quot;&gt;
        ///    &lt;Type codingScheme=&quot;SRT&quot; codeValue=&quot;T-1A190&quot; cid=&quot;7156&quot; contextGroupName=&quot;Vascular Tissue Segmentation Types&quot; SNOMED [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SegmentationCategoryTypeModifierXml {
            get {
                return ResourceManager.GetString("SegmentationCategoryTypeModifierXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:element name=&quot;SegmentationCodes&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence maxOccurs=&quot;unbounded&quot;&gt;
        ///				&lt;xs:element name=&quot;Category&quot;&gt;
        ///					&lt;xs:complexType&gt;
        ///						&lt;xs:sequence minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///							&lt;xs:element name=&quot;Type&quot;&gt;
        ///								&lt;xs:complexType&gt;
        ///									&lt;xs:sequence minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///										&lt;xs:element name= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SegmentationCategoryTypeModifierXsd {
            get {
                return ResourceManager.GetString("SegmentationCategoryTypeModifierXsd", resourceCulture);
            }
        }
    }
}
