/*L
*  Copyright Northwestern University
*  Copyright Stanford University (ATB 1.0 and ATS 1.0)
*
*  Distributed under the OSI-approved BSD 3-Clause License.
*  See http://ncip.github.com/annotation-and-image-markup/LICENSE.txt for details.
L*/

#include "AimEnum.h"
#include "util/DateTime.h"

#include "entity/Entity.h"
#include "entity/AuditTrail.h"
#include "entity/CharacteristicQuantification.h"
#include "entity/Numerical.h"
#include "entity/Quantile.h"
#include "entity/NonQuantifiable.h"
#include "entity/Scale.h"
#include "entity/Interval.h"
#include "entity/ImagingObservationCharacteristic.h"
#include "entity/ImagingPhysicalEntityCharacteristic.h"
#include "entity/ImagingPhysicalEntity.h"
#include "entity/ImagingObservationEntity.h"
#include "entity/InferenceEntity.h"
#include "entity/Parameter.h"
#include "entity/Algorithm.h"
#include "entity/Dimension.h"
#include "entity/CalculationResult.h"
#include "entity/CalculationEntity.h"
#include "entity/CompactCalculationResult.h"
#include "entity/Coordinate.h"
#include "entity/CalculationData.h"
#include "entity/ExtendedCalculationResult.h"
#include "entity/AnnotationRoleEntity.h"
#include "entity/LesionObservationEntity.h"
#include "entity/GeneralLesionObservationEntity.h"
#include "entity/TimepointLesionObservationEntity.h"
#include "entity/TaskContextEntity.h"
#include "entity/AdjudicationObservation.h"
#include "entity/AnnotationEntity.h"
#include "entity/ReferencedDicomObject.h"
#include "entity/GeneralImage.h"
#include "entity/ImagePlane.h"
#include "entity/Image.h"
#include "entity/ImageSeries.h"
#include "entity/ImageStudy.h"
#include "entity/ImageReferenceEntity.h"
#include "entity/DicomImageReferenceEntity.h"
#include "entity/UriImageReferenceEntity.h"
#include "entity/MarkupEntity.h"
#include "entity/SegmentationEntity.h"
#include "entity/DicomSegmentationEntity.h"
#include "entity/GeometricShapeEntity.h"
#include "entity/TextAnnotationEntity.h"
#include "entity/TwoDimensionSpatialCoordinate.h"
#include "entity/TwoDimensionGeometricShapeEntity.h"
#include "entity/TwoDimensionEllipse.h"
#include "entity/TwoDimensionPoint.h"
#include "entity/TwoDimensionCircle.h"
#include "entity/TwoDimensionPolyline.h"
#include "entity/TwoDimensionMultiPoint.h"
#include "entity/ThreeDimensionSpatialCoordinate.h"
#include "entity/ThreeDimensionGeometricShapeEntity.h"
#include "entity/ThreeDimensionPoint.h"
#include "entity/ThreeDimensionEllipse.h"
#include "entity/ThreeDimensionEllipsoid.h"
#include "entity/ThreeDimensionPolyline.h"
#include "entity/ThreeDimensionPolygon.h"
#include "entity/ThreeDimensionMultiPoint.h"

#include "statement/AnnotationStatement.h"
#include "statement/AbstractAnnotationStatement.h"
#include "statement/AnnotationOfAnnotationStatement.h"
#include "statement/ImageAnnotationStatement.h"
#include "entity/ImageAnnotation.h"
#include "entity/AnnotationOfAnnotation.h"

#include "entity/User.h"
#include "entity/Equipment.h"
#include "entity/Person.h"
#include "entity/AnnotationCollection.h"
#include "entity/ImageAnnotationCollection.h"
#include "entity/AnnotationOfAnnotationCollection.h"

#include "util/AimUidGenerator.h"
