//L  
// Copyright Northwestern University
// Copyright Stanford University (ATB 1.0 and ATS 1.0)
//
// Distributed under the OSI-approved BSD 3-Clause License.
// See http://ncip.github.com/annotation-and-image-markup/LICENSE.txt for details.

namespace AIM.Annotation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIM.Annotation.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM Annotation.
        /// </summary>
        internal static string AIMAnnotationButton {
            get {
                return ResourceManager.GetString("AIMAnnotationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create AIM Annotation.
        /// </summary>
        internal static string AIMAnnotationCreateButton {
            get {
                return ResourceManager.GetString("AIMAnnotationCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create AIM Annotation.
        /// </summary>
        internal static string AIMAnnotationCreateMenu {
            get {
                return ResourceManager.GetString("AIMAnnotationCreateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start AIM Annotation Creation Wizard.
        /// </summary>
        internal static string AIMAnnotationCreateTooltip {
            get {
                return ResourceManager.GetString("AIMAnnotationCreateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create AIM Annotation.
        /// </summary>
        internal static string AIMAnnotationMenu {
            get {
                return ResourceManager.GetString("AIMAnnotationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM Annotation.
        /// </summary>
        internal static string AIMAnnotationTooltip {
            get {
                return ResourceManager.GetString("AIMAnnotationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find AIM user&apos;s guide.
        /// </summary>
        internal static string AimUsersGuideNotFound {
            get {
                return ResourceManager.GetString("AimUsersGuideNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import AIM XML Annotations.
        /// </summary>
        internal static string AimXmlImportMenu {
            get {
                return ResourceManager.GetString("AimXmlImportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anatomic Entity Cannot be Empty.
        /// </summary>
        internal static string AnatomicEntityCannotBeNull {
            get {
                return ResourceManager.GetString("AnatomicEntityCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Name Cannot be Empty.
        /// </summary>
        internal static string AnnotationNameCannotBeNull {
            get {
                return ResourceManager.GetString("AnnotationNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Type must be selected.
        /// </summary>
        internal static string AnnotationTypeCannotBeNull {
            get {
                return ResourceManager.GetString("AnnotationTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Polygonal ROI.
        /// </summary>
        internal static string CommandCreatePolygonalRoi {
            get {
                return ResourceManager.GetString("CommandCreatePolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwestern University.
        /// </summary>
        internal static string EquipmentManufacturer {
            get {
                return ResourceManager.GetString("EquipmentManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM_TCGA_v3.
        /// </summary>
        internal static string EquipmentManufacturerModelName {
            get {
                return ResourceManager.GetString("EquipmentManufacturerModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM_TCGA09302010v3.
        /// </summary>
        internal static string EquipmentSoftwareVersion {
            get {
                return ResourceManager.GetString("EquipmentSoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon {0}.
        /// </summary>
        internal static string FormatPolygonName {
            get {
                return ResourceManager.GetString("FormatPolygonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM User&apos;s Guide.
        /// </summary>
        internal static string MenuAimUserGuide {
            get {
                return ResourceManager.GetString("MenuAimUserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        internal static string MenuAnnotation {
            get {
                return ResourceManager.GetString("MenuAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Annotation Details.
        /// </summary>
        internal static string ShowAnnotationDetailsMenu {
            get {
                return ResourceManager.GetString("ShowAnnotationDetailsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Available Annotations.
        /// </summary>
        internal static string ShowAnnotationListMenu {
            get {
                return ResourceManager.GetString("ShowAnnotationListMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM Annotation.
        /// </summary>
        internal static string TitleAIMCreater {
            get {
                return ResourceManager.GetString("TitleAIMCreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Polygonal ROI.
        /// </summary>
        internal static string TooltipClickFreePolygonalRoi {
            get {
                return ResourceManager.GetString("TooltipClickFreePolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import AIM XML Annotations.
        /// </summary>
        internal static string TooltipImportAimXml {
            get {
                return ResourceManager.GetString("TooltipImportAimXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Annotation Details.
        /// </summary>
        internal static string TooltipShowAnnotationDetails {
            get {
                return ResourceManager.GetString("TooltipShowAnnotationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Available Annotations.
        /// </summary>
        internal static string TooltipShowAnnotationList {
            get {
                return ResourceManager.GetString("TooltipShowAnnotationList", resourceCulture);
            }
        }
    }
}
