#region License

// Copyright (c) 2007 - 2014, Northwestern University, Vladimir Kleper, Skip Talbot
// and Pattanasak Mongkolwat.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//   Redistributions of source code must retain the above copyright notice,
//   this list of conditions and the following disclaimer.
//
//   Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
//   Neither the name of the National Cancer Institute nor Northwestern University
//   nor the names of its contributors may be used to endorse or promote products
//   derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#endregion


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace AIM.Annotation.TemplateTree.Utilities
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    [System.Xml.Serialization.XmlRootAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate", IsNullable = false)]
    public partial class TemplateContainer
    {

        private TemplateContainerTemplate[] templateField;

        private Tag[] tagsField;

        private string nameField;

        private string versionField;

        private string descriptionField;

        private string uidField;

        private string authorsField;

        private System.DateTime creationDateField;

        private bool creationDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Template")]
        public TemplateContainerTemplate[] Template
        {
            get { return this.templateField; }
            set { this.templateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Tag[] Tags
        {
            get { return this.tagsField; }
            set { this.tagsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get { return this.versionField; }
            set { this.versionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uid
        {
            get { return this.uidField; }
            set { this.uidField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authors
        {
            get { return this.authorsField; }
            set { this.authorsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime creationDate
        {
            get { return this.creationDateField; }
            set { this.creationDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateSpecified
        {
            get { return this.creationDateFieldSpecified; }
            set { this.creationDateFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateContainerTemplate : Template
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class Template
    {

        private TemplateComponent[] componentField;

        private Tag[] tagsField;

        private string nameField;

        private string versionField;

        private string descriptionField;

        private string uidField;

        private string codeValueField;

        private string codeMeaningField;

        private string codingSchemeDesignatorField;

        private string codingSchemeVersionField;

        private modalityType modalityField;

        private bool modalityFieldSpecified;

        private string authorsField;

        private System.DateTime creationDateField;

        private bool creationDateFieldSpecified;

        private PrecedingAnnotationRequest precedingAnnotationField;

        private bool precedingAnnotationFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public TemplateComponent[] Component
        {
            get { return this.componentField; }
            set { this.componentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Tag[] Tags
        {
            get { return this.tagsField; }
            set { this.tagsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get { return this.versionField; }
            set { this.versionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uid
        {
            get { return this.uidField; }
            set { this.uidField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeValue
        {
            get { return this.codeValueField; }
            set { this.codeValueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeMeaning
        {
            get { return this.codeMeaningField; }
            set { this.codeMeaningField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingSchemeDesignator
        {
            get { return this.codingSchemeDesignatorField; }
            set { this.codingSchemeDesignatorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingSchemeVersion
        {
            get { return this.codingSchemeVersionField; }
            set { this.codingSchemeVersionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public modalityType modality
        {
            get { return this.modalityField; }
            set { this.modalityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modalitySpecified
        {
            get { return this.modalityFieldSpecified; }
            set { this.modalityFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authors
        {
            get { return this.authorsField; }
            set { this.authorsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime creationDate
        {
            get { return this.creationDateField; }
            set { this.creationDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateSpecified
        {
            get { return this.creationDateFieldSpecified; }
            set { this.creationDateFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PrecedingAnnotationRequest precedingAnnotation
        {
            get { return this.precedingAnnotationField; }
            set { this.precedingAnnotationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precedingAnnotationSpecified
        {
            get { return this.precedingAnnotationFieldSpecified; }
            set { this.precedingAnnotationFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponent : Component
    {

        private ValidTerm questionTypeField;

        private object[] itemsField;

        /// <remarks/>
        public ValidTerm QuestionType
        {
            get { return this.questionTypeField; }
            set { this.questionTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllowedTerm", typeof (TemplateComponentAllowedTerm))]
        [System.Xml.Serialization.XmlElementAttribute("AnatomicEntity", typeof (TemplateComponentAnatomicEntity))]
        [System.Xml.Serialization.XmlElementAttribute("Calculation", typeof (TemplateComponentCalculation))]
        [System.Xml.Serialization.XmlElementAttribute("GeometricShape", typeof (TemplateComponentGeometricShape))]
        [System.Xml.Serialization.XmlElementAttribute("ImagingObservation", typeof (TemplateComponentImagingObservation)
            )]
        [System.Xml.Serialization.XmlElementAttribute("Inference", typeof (TemplateComponentInference))]
        public object[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class ValidTerm : CodedTerm
    {

        private ValidTerm[] validTerm1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValidTerm")]
        public ValidTerm[] ValidTerm1
        {
            get { return this.validTerm1Field; }
            set { this.validTerm1Field = value; }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof (ValidTerm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof (Algorithm))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class CodedTerm
    {

        private string codeValueField;

        private string codeMeaningField;

        private string codingSchemeDesignatorField;

        private string codingSchemeVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeValue
        {
            get { return this.codeValueField; }
            set { this.codeValueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeMeaning
        {
            get { return this.codeMeaningField; }
            set { this.codeMeaningField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingSchemeDesignator
        {
            get { return this.codingSchemeDesignatorField; }
            set { this.codingSchemeDesignatorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingSchemeVersion
        {
            get { return this.codingSchemeVersionField; }
            set { this.codingSchemeVersionField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TagValue
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CodedValue", typeof (CodedTerm))]
        [System.Xml.Serialization.XmlElementAttribute("StringValue", typeof (string))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class Tag
    {

        private CodedTerm tagNameField;

        private TagValue tagValueField;

        /// <remarks/>
        public CodedTerm TagName
        {
            get { return this.tagNameField; }
            set { this.tagNameField = value; }
        }

        /// <remarks/>
        public TagValue TagValue
        {
            get { return this.tagValueField; }
            set { this.tagValueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class Quantile
    {

        private string binsField;

        private double maxValueField;

        private double minValueField;

        private string valueLabelField;

        private string valueDescriptionField;

        private string defaultBinField;

        private string nextIdField;

        private bool noMoreQuestionsField;

        public Quantile()
        {
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string bins
        {
            get { return this.binsField; }
            set { this.binsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double maxValue
        {
            get { return this.maxValueField; }
            set { this.maxValueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double minValue
        {
            get { return this.minValueField; }
            set { this.minValueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueLabel
        {
            get { return this.valueLabelField; }
            set { this.valueLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueDescription
        {
            get { return this.valueDescriptionField; }
            set { this.valueDescriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string defaultBin
        {
            get { return this.defaultBinField; }
            set { this.defaultBinField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class Interval
    {

        private double minValueField;

        private double maxValueField;

        private @operator minOperatorField;

        private @operator maxOperatorField;

        private string ucumStringField;

        private string valueLabelField;

        private string valueDescriptionField;

        private bool askForInputField;

        private bool defaultAnswerField;

        private string nextIdField;

        private bool noMoreQuestionsField;

        private string valueField;

        public Interval()
        {
            this.askForInputField = false;
            this.defaultAnswerField = false;
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double minValue
        {
            get { return this.minValueField; }
            set { this.minValueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double maxValue
        {
            get { return this.maxValueField; }
            set { this.maxValueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public @operator minOperator
        {
            get { return this.minOperatorField; }
            set { this.minOperatorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public @operator maxOperator
        {
            get { return this.maxOperatorField; }
            set { this.maxOperatorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ucumString
        {
            get { return this.ucumStringField; }
            set { this.ucumStringField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueLabel
        {
            get { return this.valueLabelField; }
            set { this.valueLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueDescription
        {
            get { return this.valueDescriptionField; }
            set { this.valueDescriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool askForInput
        {
            get { return this.askForInputField; }
            set { this.askForInputField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool defaultAnswer
        {
            get { return this.defaultAnswerField; }
            set { this.defaultAnswerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public enum @operator
    {

        /// <remarks/>
        Equal,

        /// <remarks/>
        NotEqual,

        /// <remarks/>
        LessThan,

        /// <remarks/>
        GreaterThan,

        /// <remarks/>
        LessThanEqual,

        /// <remarks/>
        GreaterThanEqual,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class Numerical
    {

        private double valueField;

        private string ucumStringField;

        private @operator operatorField;

        private bool operatorFieldSpecified;

        private string valueLabelField;

        private string valueDescriptionField;

        private bool askForInputField;

        private bool defaultAnswerField;

        private string nextIdField;

        private bool noMoreQuestionsField;

        private string valueField1;

        public Numerical()
        {
            this.askForInputField = false;
            this.defaultAnswerField = false;
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ucumString
        {
            get { return this.ucumStringField; }
            set { this.ucumStringField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public @operator @operator
        {
            get { return this.operatorField; }
            set { this.operatorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified
        {
            get { return this.operatorFieldSpecified; }
            set { this.operatorFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueLabel
        {
            get { return this.valueLabelField; }
            set { this.valueLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueDescription
        {
            get { return this.valueDescriptionField; }
            set { this.valueDescriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool askForInput
        {
            get { return this.askForInputField; }
            set { this.askForInputField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool defaultAnswer
        {
            get { return this.defaultAnswerField; }
            set { this.defaultAnswerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField1; }
            set { this.valueField1 = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class Scale
    {

        private ScaleScaleLevel[] scaleLevelField;

        private ScaleType scaleTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScaleLevel")]
        public ScaleScaleLevel[] ScaleLevel
        {
            get { return this.scaleLevelField; }
            set { this.scaleLevelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ScaleType scaleType
        {
            get { return this.scaleTypeField; }
            set { this.scaleTypeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class ScaleScaleLevel
    {

        private string valueField;

        private string valueLabelField;

        private string valueDescriptionField;

        private bool defaultAnswerField;

        private string nextIdField;

        private bool noMoreQuestionsField;

        public ScaleScaleLevel()
        {
            this.defaultAnswerField = false;
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueLabel
        {
            get { return this.valueLabelField; }
            set { this.valueLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueDescription
        {
            get { return this.valueDescriptionField; }
            set { this.valueDescriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool defaultAnswer
        {
            get { return this.defaultAnswerField; }
            set { this.defaultAnswerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public enum ScaleType
    {

        /// <remarks/>
        Nominal,

        /// <remarks/>
        Ordinal,

        /// <remarks/>
        Ratio,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class CharacteristicQuantification
    {

        private string nameField;

        private bool annotatorConfidenceField;

        private string characteristicQuantificationIndexField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool annotatorConfidence
        {
            get { return this.annotatorConfidenceField; }
            set { this.annotatorConfidenceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string characteristicQuantificationIndex
        {
            get { return this.characteristicQuantificationIndexField; }
            set { this.characteristicQuantificationIndexField = value; }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof (ImagingObservationCharacteristic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof (AnatomicEntityCharacteristic))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public abstract partial class ComponentCharacteristic
    {

        private ComponentCharacteristicAllowedTerm[] allowedTermField;

        private string labelField;

        private string minCardinalityField;

        private string maxCardinalityField;

        private string itemNumberField;

        private bool shouldDisplayField;

        private string explanatoryTextField;

        private string authorsField;

        private string groupLabelField;

        private string idField;

        private bool requireCommentField;

        private bool requireCommentFieldSpecified;

        public ComponentCharacteristic()
        {
            this.groupLabelField = "";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllowedTerm")]
        public ComponentCharacteristicAllowedTerm[] AllowedTerm
        {
            get { return this.allowedTermField; }
            set { this.allowedTermField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label
        {
            get { return this.labelField; }
            set { this.labelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string minCardinality
        {
            get { return this.minCardinalityField; }
            set { this.minCardinalityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string maxCardinality
        {
            get { return this.maxCardinalityField; }
            set { this.maxCardinalityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string itemNumber
        {
            get { return this.itemNumberField; }
            set { this.itemNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool shouldDisplay
        {
            get { return this.shouldDisplayField; }
            set { this.shouldDisplayField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string explanatoryText
        {
            get { return this.explanatoryTextField; }
            set { this.explanatoryTextField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authors
        {
            get { return this.authorsField; }
            set { this.authorsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string groupLabel
        {
            get { return this.groupLabelField; }
            set { this.groupLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool requireComment
        {
            get { return this.requireCommentField; }
            set { this.requireCommentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requireCommentSpecified
        {
            get { return this.requireCommentFieldSpecified; }
            set { this.requireCommentFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class ComponentCharacteristicAllowedTerm : ValidTerm
    {

        private ComponentCharacteristicAllowedTermCharacteristicQuantification[] characteristicQuantificationField;

        private bool defaultAnswerField;

        private string nextIdField;

        private bool noMoreQuestionsField;

        public ComponentCharacteristicAllowedTerm()
        {
            this.defaultAnswerField = false;
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CharacteristicQuantification")]
        public ComponentCharacteristicAllowedTermCharacteristicQuantification[] CharacteristicQuantification
        {
            get { return this.characteristicQuantificationField; }
            set { this.characteristicQuantificationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool defaultAnswer
        {
            get { return this.defaultAnswerField; }
            set { this.defaultAnswerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class ComponentCharacteristicAllowedTermCharacteristicQuantification : CharacteristicQuantification
    {

        private object[] itemsField;

        private ComponentCharacteristicAllowedTermCharacteristicQuantificationNonQuantifiable[] nonQuantifiableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Interval", typeof (Interval))]
        [System.Xml.Serialization.XmlElementAttribute("Numerical", typeof (Numerical))]
        [System.Xml.Serialization.XmlElementAttribute("Quantile", typeof (Quantile))]
        [System.Xml.Serialization.XmlElementAttribute("Scale", typeof (Scale))]
        public object[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NonQuantifiable")]
        public ComponentCharacteristicAllowedTermCharacteristicQuantificationNonQuantifiable[] NonQuantifiable
        {
            get { return this.nonQuantifiableField; }
            set { this.nonQuantifiableField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class ComponentCharacteristicAllowedTermCharacteristicQuantificationNonQuantifiable
    {

        private string codeValueField;

        private string codeMeaningField;

        private string codingSchemeDesignatorField;

        private string codingSchemeVersionField;

        private string valueDescriptionField;

        private bool defaultAnswerField;

        private string nextIdField;

        private bool noMoreQuestionsField;

        public ComponentCharacteristicAllowedTermCharacteristicQuantificationNonQuantifiable()
        {
            this.defaultAnswerField = false;
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeValue
        {
            get { return this.codeValueField; }
            set { this.codeValueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeMeaning
        {
            get { return this.codeMeaningField; }
            set { this.codeMeaningField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingSchemeDesignator
        {
            get { return this.codingSchemeDesignatorField; }
            set { this.codingSchemeDesignatorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codingSchemeVersion
        {
            get { return this.codingSchemeVersionField; }
            set { this.codingSchemeVersionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueDescription
        {
            get { return this.valueDescriptionField; }
            set { this.valueDescriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool defaultAnswer
        {
            get { return this.defaultAnswerField; }
            set { this.defaultAnswerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class ImagingObservationCharacteristic : ComponentCharacteristic
    {

        private bool annotatorConfidenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool annotatorConfidence
        {
            get { return this.annotatorConfidenceField; }
            set { this.annotatorConfidenceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class AnatomicEntityCharacteristic : ComponentCharacteristic
    {

        private bool annotatorConfidenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool annotatorConfidence
        {
            get { return this.annotatorConfidenceField; }
            set { this.annotatorConfidenceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public abstract partial class Component
    {

        private string labelField;

        private string minCardinalityField;

        private string maxCardinalityField;

        private string itemNumberField;

        private bool shouldDisplayField;

        private string explanatoryTextField;

        private string authorsField;

        private string groupLabelField;

        private string idField;

        private bool requireCommentField;

        private bool requireCommentFieldSpecified;

        public Component()
        {
            this.groupLabelField = "";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label
        {
            get { return this.labelField; }
            set { this.labelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string minCardinality
        {
            get { return this.minCardinalityField; }
            set { this.minCardinalityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string maxCardinality
        {
            get { return this.maxCardinalityField; }
            set { this.maxCardinalityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string itemNumber
        {
            get { return this.itemNumberField; }
            set { this.itemNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool shouldDisplay
        {
            get { return this.shouldDisplayField; }
            set { this.shouldDisplayField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string explanatoryText
        {
            get { return this.explanatoryTextField; }
            set { this.explanatoryTextField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authors
        {
            get { return this.authorsField; }
            set { this.authorsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string groupLabel
        {
            get { return this.groupLabelField; }
            set { this.groupLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool requireComment
        {
            get { return this.requireCommentField; }
            set { this.requireCommentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requireCommentSpecified
        {
            get { return this.requireCommentFieldSpecified; }
            set { this.requireCommentFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class Algorithm : CodedTerm
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentAllowedTerm : ValidTerm
    {

        private bool defaultAnswerField;

        private string nextIdField;

        private bool noMoreQuestionsField;

        public TemplateComponentAllowedTerm()
        {
            this.defaultAnswerField = false;
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool defaultAnswer
        {
            get { return this.defaultAnswerField; }
            set { this.defaultAnswerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentAnatomicEntity
    {

        private TemplateComponentAnatomicEntityAnatomicEntityCharacteristic[] anatomicEntityCharacteristicField;

        private TemplateComponentAnatomicEntityImagingObservationCharacteristic[] imagingObservationCharacteristicField;

        private bool annotatorConfidenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnatomicEntityCharacteristic")]
        public TemplateComponentAnatomicEntityAnatomicEntityCharacteristic[] AnatomicEntityCharacteristic
        {
            get { return this.anatomicEntityCharacteristicField; }
            set { this.anatomicEntityCharacteristicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImagingObservationCharacteristic")]
        public TemplateComponentAnatomicEntityImagingObservationCharacteristic[] ImagingObservationCharacteristic
        {
            get { return this.imagingObservationCharacteristicField; }
            set { this.imagingObservationCharacteristicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool annotatorConfidence
        {
            get { return this.annotatorConfidenceField; }
            set { this.annotatorConfidenceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentAnatomicEntityAnatomicEntityCharacteristic : AnatomicEntityCharacteristic
    {

        private ValidTerm questionTypeField;

        /// <remarks/>
        public ValidTerm QuestionType
        {
            get { return this.questionTypeField; }
            set { this.questionTypeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentAnatomicEntityImagingObservationCharacteristic :
        ImagingObservationCharacteristic
    {

        private ValidTerm questionTypeField;

        /// <remarks/>
        public ValidTerm QuestionType
        {
            get { return this.questionTypeField; }
            set { this.questionTypeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentCalculation
    {

        private TemplateComponentCalculationCalculationType[] calculationTypeField;

        private bool noMoreQuestionsField;

        private string nextIdField;

        public TemplateComponentCalculation()
        {
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalculationType")]
        public TemplateComponentCalculationCalculationType[] CalculationType
        {
            get { return this.calculationTypeField; }
            set { this.calculationTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentCalculationCalculationType : ValidTerm
    {

        private TemplateComponentCalculationCalculationTypeAlgorithmType[] algorithmTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlgorithmType")]
        public TemplateComponentCalculationCalculationTypeAlgorithmType[] AlgorithmType
        {
            get { return this.algorithmTypeField; }
            set { this.algorithmTypeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentCalculationCalculationTypeAlgorithmType : CodedTerm
    {

        private string descriptionField;

        private string uniqueIdentifierField;

        private string algorithmNameField;

        private string algorithmVersionField;

        private string mathMLField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uniqueIdentifier
        {
            get { return this.uniqueIdentifierField; }
            set { this.uniqueIdentifierField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string algorithmName
        {
            get { return this.algorithmNameField; }
            set { this.algorithmNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string algorithmVersion
        {
            get { return this.algorithmVersionField; }
            set { this.algorithmVersionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mathML
        {
            get { return this.mathMLField; }
            set { this.mathMLField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentGeometricShape
    {

        private bool noMoreQuestionsField;

        private string nextIdField;

        private GeometricShape valueField;

        public TemplateComponentGeometricShape()
        {
            this.noMoreQuestionsField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noMoreQuestions
        {
            get { return this.noMoreQuestionsField; }
            set { this.noMoreQuestionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nextId
        {
            get { return this.nextIdField; }
            set { this.nextIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public GeometricShape Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public enum GeometricShape
    {

        /// <remarks/>
        Point,

        /// <remarks/>
        Circle,

        /// <remarks/>
        Polyline,

        /// <remarks/>
        Ellipse,

        /// <remarks/>
        MultiPoint,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3DPolygon")] Item3DPolygon,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3DPolyline")] Item3DPolyline,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3DMultiPoint")] Item3DMultiPoint,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3DPoint")] Item3DPoint,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3DEllipse")] Item3DEllipse,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3DEllipsoid")] Item3DEllipsoid,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentImagingObservation
    {

        private TemplateComponentImagingObservationImagingObservationCharacteristic[]
            imagingObservationCharacteristicField;

        private bool annotatorConfidenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImagingObservationCharacteristic")]
        public TemplateComponentImagingObservationImagingObservationCharacteristic[] ImagingObservationCharacteristic
        {
            get { return this.imagingObservationCharacteristicField; }
            set { this.imagingObservationCharacteristicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool annotatorConfidence
        {
            get { return this.annotatorConfidenceField; }
            set { this.annotatorConfidenceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentImagingObservationImagingObservationCharacteristic :
        ImagingObservationCharacteristic
    {

        private ValidTerm questionTypeField;

        /// <remarks/>
        public ValidTerm QuestionType
        {
            get { return this.questionTypeField; }
            set { this.questionTypeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public partial class TemplateComponentInference
    {

        private bool annotatorConfidenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool annotatorConfidence
        {
            get { return this.annotatorConfidenceField; }
            set { this.annotatorConfidenceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public enum modalityType
    {

        /// <remarks/>
        AU,

        /// <remarks/>
        BDUS,

        /// <remarks/>
        BI,

        /// <remarks/>
        BMD,

        /// <remarks/>
        CD,

        /// <remarks/>
        CR,

        /// <remarks/>
        CT,

        /// <remarks/>
        DD,

        /// <remarks/>
        DOC,

        /// <remarks/>
        DG,

        /// <remarks/>
        DX,

        /// <remarks/>
        ECG,

        /// <remarks/>
        EPS,

        /// <remarks/>
        ES,

        /// <remarks/>
        GM,

        /// <remarks/>
        HC,

        /// <remarks/>
        HD,

        /// <remarks/>
        IO,

        /// <remarks/>
        IVUS,

        /// <remarks/>
        KO,

        /// <remarks/>
        LS,

        /// <remarks/>
        MG,

        /// <remarks/>
        MR,

        /// <remarks/>
        NM,

        /// <remarks/>
        OCT,

        /// <remarks/>
        OT,

        /// <remarks/>
        OP,

        /// <remarks/>
        OPM,

        /// <remarks/>
        OPT,

        /// <remarks/>
        OPR,

        /// <remarks/>
        OPV,

        /// <remarks/>
        PR,

        /// <remarks/>
        PT,

        /// <remarks/>
        PX,

        /// <remarks/>
        REG,

        /// <remarks/>
        RG,

        /// <remarks/>
        RTDOSE,

        /// <remarks/>
        RTIMAGE,

        /// <remarks/>
        RTPLAN,

        /// <remarks/>
        RTSTRUCT,

        /// <remarks/>
        RTRECORD,

        /// <remarks/>
        SEG,

        /// <remarks/>
        SM,

        /// <remarks/>
        SMR,

        /// <remarks/>
        SR,

        /// <remarks/>
        ST,

        /// <remarks/>
        US,

        /// <remarks/>
        XA,

        /// <remarks/>
        XC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "gme://caCORE.caCORE/3.2/edu.northwestern.radiology.AIMTemplate")]
    public enum PrecedingAnnotationRequest
    {

        /// <remarks/>
        OfferToSelect,

        /// <remarks/>
        RequireToSelect,

        /// <remarks/>
        DoNotOffer,
    }
}
