/*
*  2007 – 2013 Copyright Northwestern University
*
*  Distributed under the OSI-approved BSD 3-Clause License.
*  See http://ncip.github.com/annotation-and-image-markup/LICENSE.txt for details.
*/

#pragma once
#ifndef _AIMLib_ImageAnnotationStatement_Class_
#define _AIMLib_ImageAnnotationStatement_Class_

namespace aim_lib
{
	//typedef AnnotationStatement ImageAnnotationStatement;
	class AIMLIB_API ImageAnnotationStatement : public AnnotationStatement
	{
	public:
		virtual ~ImageAnnotationStatement(void){
		}
	protected:
		ImageAnnotationStatement(void){
		}

		ImageAnnotationStatement(const iso_21090::II& subjectUid, const iso_21090::II& objectUid) : AnnotationStatement(subjectUid, objectUid){
		}

		ImageAnnotationStatement(const ImageAnnotationStatement& statement) : AnnotationStatement(statement){
		}
	};

	typedef std::vector<AnnotationStatement*> ImageAnnotationStatementPtrVector;

	class ImageAnnotation;

	// Using macro
	AIM_STMT_DECL(DicomImageReferenceEntityHasCalculationEntityStatement, DicomImageReferenceEntity, CalculationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(DicomImageReferenceEntityHasImagingObservationEntityStatement, DicomImageReferenceEntity, ImagingObservationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(DicomImageReferenceEntityHasImagingPhysicalEntityStatement, DicomImageReferenceEntity, ImagingPhysicalEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(DicomSegmentationEntityHasImagingObservationEntityStatement, DicomSegmentationEntity, ImagingObservationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(GeneralLesionObservationEntityHasImagingPhysicalEntityStatement, GeneralLesionObservationEntity, ImagingPhysicalEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasCalculationEntityStatement, ImageAnnotation, CalculationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasChildImageAnnotationStatement, ImageAnnotation, ImageAnnotation, HasChildAnnotationStatementRelationship, ImageAnnotationStatement)
	
	AIM_STMT_DECL(ImageAnnotationHasDicomImageReferenceEntityStatement, ImageAnnotation, DicomImageReferenceEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasDicomSegmentationEntityStatement, ImageAnnotation, DicomSegmentationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasGeneralLesionObservationEntityStatement, ImageAnnotation, GeneralLesionObservationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasImagingObservationEntityStatement, ImageAnnotation, ImagingObservationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasImagingPhysicalEntityStatement, ImageAnnotation, ImagingPhysicalEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasInferenceEntityStatement, ImageAnnotation, InferenceEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasTextAnnotationEntityStatement, ImageAnnotation, TextAnnotationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasThreeDimensionGeometricShapeEntityStatement, ImageAnnotation, ThreeDimensionGeometricShapeEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasTwoDimensionGeometricShapeEntityStatement, ImageAnnotation, TwoDimensionGeometricShapeEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasTimePointLesionObservationEntityStatement, ImageAnnotation, TimePointLesionObservationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImageAnnotationHasUriImageReferenceEntityStatement, ImageAnnotation, UriImageReferenceEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	
	AIM_STMT_DECL(ImagingObservationEntityIsIdentifiedByThreeDimensionGeometricShapeEntityStatement, ImagingObservationEntity, ThreeDimensionGeometricShapeEntity, IsIdentifiedByAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImagingObservationEntityIsIdentifiedByTwoDimensionGeometricShapeEntityStatement, ImagingObservationEntity, TwoDimensionGeometricShapeEntity, IsIdentifiedByAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImagingObservationEntityIsIdentifiedByTextAnnotationEntityStatement, ImagingObservationEntity, TextAnnotationEntity, IsIdentifiedByAnnotationStatementRelationship, ImageAnnotationStatement)
	
	AIM_STMT_DECL(ImagingPhysicalEntityHasThreeDimensionGeometricShapeEntityStatement, ImagingPhysicalEntity, ThreeDimensionGeometricShapeEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImagingPhysicalEntityHasTwoDimensionGeometricShapeEntityStatement, ImagingPhysicalEntity, TwoDimensionGeometricShapeEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ImagingPhysicalEntityHasTextAnnotationEntityStatement, ImagingPhysicalEntity, TextAnnotationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	
	AIM_STMT_DECL(ThreeDimensionGeometricShapeEntityIsComprisedOfThreeDimensionGeometricShapeEntityStatement, ThreeDimensionGeometricShapeEntity, ThreeDimensionGeometricShapeEntity, IsComprisedOfAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(ThreeDimensionGeometricShapeEntityExcludesThreeDimensionGeometricShapeEntityStatement, ThreeDimensionGeometricShapeEntity, ThreeDimensionGeometricShapeEntity, ExcludesAnnotationStatementRelationship, ImageAnnotationStatement)
	
	AIM_STMT_DECL(TimePointLesionObservationEntityHasImagingPhysicalEntityStatement, TimePointLesionObservationEntity, ImagingPhysicalEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)

	AIM_STMT_DECL(TwoDimensionGeometricShapeEntityIsComprisedOfTwoDimensionGeometricShapeEntityStatement, TwoDimensionGeometricShapeEntity, TwoDimensionGeometricShapeEntity, IsComprisedOfAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(TwoDimensionGeometricShapeEntityExcludesTwoDimensionGeometricShapeEntityStatement, TwoDimensionGeometricShapeEntity, TwoDimensionGeometricShapeEntity, ExcludesAnnotationStatementRelationship, ImageAnnotationStatement)
	
	AIM_STMT_DECL(UriImageReferenceEntityHasImagingObservationEntityStatement, UriImageReferenceEntity, ImagingObservationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(UriImageReferenceEntityHasImagingPhysicalEntityStatement, UriImageReferenceEntity, ImagingPhysicalEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
	AIM_STMT_DECL(UriImageReferenceEntityHasCalculationEntityStatement, UriImageReferenceEntity, CalculationEntity, HasAnnotationStatementRelationship, ImageAnnotationStatement)
}
#endif // _AIMLib_ImageAnnotationStatement_Class_
