//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XnatWebBrowser.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class XnatSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static XnatSettings defaultInstance = ((XnatSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new XnatSettings())));
        
        public static XnatSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://central.xnat.org")]
        public string XnatUrl {
            get {
                return ((string)(this["XnatUrl"]));
            }
            set {
                this["XnatUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadFolder {
            get {
                return ((string)(this["DownloadFolder"]));
            }
            set {
                this["DownloadFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DownloadCheckInterval {
            get {
                return ((int)(this["DownloadCheckInterval"]));
            }
            set {
                this["DownloadCheckInterval"] = value;
            }
        }
    }
}
