//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Segmentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Segmentation.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentation Graphic ({0} #{1}, Fr #{2}).
        /// </summary>
        internal static string FormatDefaultMultiFrameSegmentationGraphicName {
            get {
                return ResourceManager.GetString("FormatDefaultMultiFrameSegmentationGraphicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentation Graphic ({0} #{1}).
        /// </summary>
        internal static string FormatDefaultSingleFrameSegmentationGraphicName {
            get {
                return ResourceManager.GetString("FormatDefaultSingleFrameSegmentationGraphicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentation.
        /// </summary>
        internal static string MenuSegmentation {
            get {
                return ResourceManager.GetString("MenuSegmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentation.
        /// </summary>
        internal static string SegmentationButton {
            get {
                return ResourceManager.GetString("SegmentationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Segmentation.
        /// </summary>
        internal static string SegmentationMenu {
            get {
                return ResourceManager.GetString("SegmentationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentation.
        /// </summary>
        internal static string SegmentationTitle {
            get {
                return ResourceManager.GetString("SegmentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentation.
        /// </summary>
        internal static string SegmentationTooltip {
            get {
                return ResourceManager.GetString("SegmentationTooltip", resourceCulture);
            }
        }
    }
}
